server:
  port: 80

spring:
  # database config
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://8.129.222.205:3306/yczuoxin
    username: zuoxin
    password: root

# logger config
logging:
  level:
    com.baomidou.mybatisplus.samples: debug