server:
  port: 80

spring:
  # database config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://8.129.222.205:3306/yczuoxin
    username: zuoxin
    password: root

web:
  aaa: 123

# logger config
logging:
  level:
    com.baomidou.mybatisplus.samples: debug

processor:
  mapper:
    generateEnable: true